version: 2
jobs:
  build:
    docker:
      - image: quay.io/giantswarm/golang:1.11.3
    working_directory: /workdir
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run: go test ./...
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
