version: 2

jobs:
  build-binary:
    docker:
      - image: quay.io/giantswarm/golang:1.11.3
    working_directory: /workdir
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run: |
          CGO_ENABLED=0 go test -ldflags "-w -X main.gitCommit=${CIRCLE_SHA1} -linkmode 'auto' -extldflags '-static'" ./...
      - run: |
          CGO_ENABLED=0 go build -ldflags "-w -X main.gitCommit=${CIRCLE_SHA1} -linkmode 'auto' -extldflags '-static'" -o devctl .
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run: |
          ./devctl version
      - persist_to_workspace:
          root: .
          paths:
            - ./devctl
  deploy-image:
    docker:
      - image: docker:18.09.1 # TODO add to retagger
    working_directory: /workdir
    steps:
      - checkout
      - attach_workspace:
          at: .
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          docker version
      - run: |
          docker build --tag quay.io/giantswarm/devctl .

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-binary
      - deploy-image:
          requires:
            - build-binary
