version: 2.1

orbs:
  architect: giantswarm/architect@4.34.1

workflows:
  go-build:
    jobs:
      - architect/go-build:
          name: go-build-devctl
          binary: devctl
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          name: push-devctl-to-quay
          context: architect
          image: "quay.io/giantswarm/devctl"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - go-build-devctl
          filters:
            # Needed to trigger job also on git tag.
            tags:
              only: /^v.*/
