version: 2.1

orbs:
  architect: giantswarm/architect@4.37.0

workflows:
  go-build:
    jobs:
      - architect/go-build:
          name: go-build-devctl
          binary: devctl
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          requires:
            - go-build-devctl
          filters:
            # Needed to trigger job also on git tag.
            tags:
              only: /^v.*/
