package reservation

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/giantswarm/microerror"
	"gopkg.in/yaml.v3"
)

// generatedBy heads every file the reservation owns.
const generatedBy = "# Generated by `devctl reservation reserve`. Do not edit.\n"

var (
	// flowFold matches the line break the YAML emitter inserts into a long flow
	// mapping. In flow context a break folds to a single space.
	flowFold = regexp.MustCompile(`\n\s*`)
	// dataKey matches a key inside the ConfigMap data block.
	dataKey = regexp.MustCompile(`^\s+([A-Za-z0-9][A-Za-z0-9.\-_]*)\s*:`)
)

// flowMapping renders the fields as a single-line YAML flow mapping, with the
// quoting YAML needs for the values it was given.
func flowMapping(fields [][2]string) (string, error) {
	node := &yaml.Node{Kind: yaml.MappingNode, Style: yaml.FlowStyle}
	for _, f := range fields {
		node.Content = append(node.Content,
			&yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: f[0]},
			&yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: f[1]},
		)
	}

	out, err := yaml.Marshal(node)
	if err != nil {
		return "", microerror.Mask(err)
	}

	return flowFold.ReplaceAllString(strings.TrimSpace(string(out)), " "), nil
}

// marshalYAML encodes v at the two-space indentation these repos use.
func marshalYAML(v any) ([]byte, error) {
	var buf bytes.Buffer
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(v); err != nil {
		return nil, microerror.Mask(err)
	}
	if err := enc.Close(); err != nil {
		return nil, microerror.Mask(err)
	}

	return buf.Bytes(), nil
}

// writeComponent writes the reservation's own Kustomize component: the new
// source object, and the strategic-merge patch that points the app's release at
// it.
func writeComponent(dir, sourceName string, helmReleases []string, source object) error {
	if err := os.MkdirAll(dir, 0o755); err != nil { //nolint:gosec // the GitOps repo is a checkout humans and Flux read
		return microerror.Mask(err)
	}

	sourceYAML, err := marshalYAML(map[string]any(source))
	if err != nil {
		return microerror.Mask(err)
	}
	if err := os.WriteFile(filepath.Join(dir, sourceName+".yaml"), append([]byte(generatedBy), sourceYAML...), 0o644); err != nil { //nolint:gosec // a file committed to a GitOps repo
		return microerror.Mask(err)
	}

	// One patch per instance. An app can run several times on one cluster, and
	// all its instances share the chart and the branch, so they share the one
	// source object above.
	//
	// A strategic-merge patch, not a JSON6902 one: the shape of the release
	// differs between stages, so an op-based patch would need per-stage
	// branching.
	var patches strings.Builder
	for _, name := range helmReleases {
		fmt.Fprintf(&patches, `  - patch: |
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: %s
      metadata:
        name: %s
        namespace: %s
      spec:
        chartRef:
          name: %s
`, helmReleaseKind, name, Namespace, sourceName)
	}

	component := generatedBy + fmt.Sprintf(`apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - %s.yaml
patches:
%s`, sourceName, patches.String())

	return microerror.Mask(os.WriteFile(filepath.Join(dir, "kustomization.yaml"), []byte(component), 0o644)) //nolint:gosec // a file committed to a GitOps repo
}

// addComponent appends entry to the components list of a kustomization file. It
// edits the text rather than re-encoding the document, so releasing the
// reservation restores the file byte for byte and a hand-written comment
// survives.
func addComponent(path, entry string) error {
	lines, err := readLines(path)
	if err != nil {
		return microerror.Mask(err)
	}

	start := -1
	for i, l := range lines {
		switch strings.TrimSpace(l) {
		case "components:":
			start = i
		case "components: []":
			lines[i] = "components:"
			start = i
		}
		if start >= 0 {
			break
		}
	}

	if start < 0 {
		lines = append(trimTrailingBlank(lines), "components:", "  - "+entry, "")
		return microerror.Mask(writeLines(path, lines))
	}

	last, indent := start, "  "
	for i := start + 1; i < len(lines); i++ {
		if strings.TrimSpace(lines[i]) == "" {
			continue
		}
		if lines[i] == strings.TrimLeft(lines[i], " \t") {
			break // a line at the outer indentation ends the block
		}
		if item := strings.TrimSpace(lines[i]); strings.HasPrefix(item, "- ") {
			if item == "- "+entry {
				return nil
			}
			last = i
			indent = lines[i][:len(lines[i])-len(strings.TrimLeft(lines[i], " \t"))]
		}
	}

	lines = append(lines[:last+1], append([]string{indent + "- " + entry}, lines[last+1:]...)...)

	return microerror.Mask(writeLines(path, lines))
}

// dataBlock locates the ConfigMap `data:` key and the last line that belongs to
// it. It reports false when the file carries no data key.
func dataBlock(lines []string) (start, last int, ok bool) {
	start = -1
	for i, l := range lines {
		if s := strings.TrimSpace(l); s == "data:" || s == "data: {}" {
			start = i
			break
		}
	}
	if start < 0 {
		return 0, 0, false
	}

	last = start
	for i := start + 1; i < len(lines); i++ {
		if strings.TrimSpace(lines[i]) == "" {
			continue
		}
		if lines[i] == strings.TrimLeft(lines[i], " \t") {
			break // a line at the outer indentation ends the block
		}
		if dataKey.MatchString(lines[i]) {
			last = i
		}
	}

	return start, last, true
}

// findEntry returns the reservation entry app already holds, if any.
func findEntry(lines []string, app string) (string, bool) {
	start, last, ok := dataBlock(lines)
	if !ok {
		return "", false
	}
	for i := start + 1; i <= last; i++ {
		if m := dataKey.FindStringSubmatch(lines[i]); m != nil && m[1] == app {
			return strings.TrimSpace(lines[i]), true
		}
	}

	return "", false
}

// checkNotReserved refuses an app that already holds a reservation on the
// cluster. One entry per app is the lock, and it is checked before anything is
// written so the second caller is told who holds it rather than which file
// failed to render.
func checkNotReserved(path, app string) error {
	lines, err := readLines(path)
	if err != nil {
		return microerror.Mask(err)
	}
	if entry, ok := findEntry(lines, app); ok {
		return microerror.Maskf(alreadyReservedError,
			"%q already holds a reservation on this cluster: %s", app, entry)
	}

	return nil
}

// addReservationEntry adds one reservation to the ConfigMap data block.
func addReservationEntry(path, app, entry string) error {
	lines, err := readLines(path)
	if err != nil {
		return microerror.Mask(err)
	}

	start, last, ok := dataBlock(lines)
	if !ok {
		return microerror.Maskf(invalidConfigError, "%s holds no `data:` key", path)
	}
	if held, ok := findEntry(lines, app); ok {
		return microerror.Maskf(alreadyReservedError,
			"%q already holds a reservation on this cluster: %s", app, held)
	}
	lines[start] = "data:"

	lines = append(lines[:last+1], append([]string{"  " + entry}, lines[last+1:]...)...)

	return microerror.Mask(writeLines(path, lines))
}

func readLines(path string) ([]string, error) {
	b, err := os.ReadFile(path) //nolint:gosec // the path is built from the repo checkout and the cluster name
	if err != nil {
		return nil, microerror.Mask(err)
	}

	return strings.Split(string(b), "\n"), nil
}

func writeLines(path string, lines []string) error {
	return os.WriteFile(path, []byte(strings.Join(lines, "\n")), 0o644) //nolint:gosec // a file committed to a GitOps repo
}

func trimTrailingBlank(lines []string) []string {
	for len(lines) > 0 && strings.TrimSpace(lines[len(lines)-1]) == "" {
		lines = lines[:len(lines)-1]
	}

	return lines
}
