name: lint-changelog

on:
  pull_request:
    paths:
      - CHANGELOG.md

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        fetch-depth: '0'
    - name: Install dependencies
      run: |
        pip install parse-changelog
        sudo apt-get install --yes jq
    - name: Parse changelog
      run: parse-changelog --changelog ./CHANGELOG.md
