name: lint-changelog

on:
  pull_request:
    paths:
      - /CHANGELOG.md

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'
    - run: pip install parse-changelog
    - run: pwd
    - run: ls -la
    - run: echo $GITHUB_WORKSPACE
